# Generated by Django 4.1.1 on 2022-09-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_delete_student_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo_img',
            field=models.ImageField(default='default', upload_to='photos'),
        ),
    ]
