# Generated by Django 4.1.1 on 2022-09-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_course_photo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo_img',
            field=models.ImageField(blank=True, default='default', null=True, upload_to='photos'),
        ),
    ]
