# Generated by Django 4.1.1 on 2022-09-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_course_photo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_detail',
            field=models.TextField(null=True),
        ),
    ]
