# Generated by Django 4.1.1 on 2022-09-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_course_course_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=100)),
                ('photo_img', models.ImageField(blank=True, default='default', null=True, upload_to='photos')),
                ('courses', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_course', to='app1.course')),
            ],
        ),
    ]
