# Generated by Django 4.1.1 on 2022-09-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_maincourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='question_sets',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
