# Generated by Django 4.1.1 on 2022-09-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_course_question_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='question_sets',
            field=models.IntegerField(default=0),
        ),
    ]
