# Generated by Django 4.1.1 on 2022-09-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_course_question_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
