# Generated by Django 4.1.1 on 2022-10-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
